// GENERATED by build-config.js from .env — do not edit, do not commit.
window.firebaseConfig = {
  "apiKey": "AIzaSyBJ8-brW_T9zzeWjzZTAhXnlrxG3wDrwlI",
  "authDomain": "online-store-fc218.firebaseapp.com",
  "projectId": "online-store-fc218",
  "storageBucket": "online-store-fc218.appspot.com",
  "messagingSenderId": "307608454112",
  "appId": "1:307608454112:web:0807aab2d9ce964ec46185"
};
