#!/usr/bin/env node
// Generates firebase-config.js from .env (or from process env vars in CI).
// Usage: node build-config.js     (run before serving / deploying)
const fs = require("fs");
const path = require("path");

const envPath = path.join(__dirname, ".env");
if (fs.existsSync(envPath)) {
  for (const line of fs.readFileSync(envPath, "utf8").split("\n")) {
    const m = line.match(/^\s*([A-Z0-9_]+)\s*=\s*(.*)\s*$/);
    if (m && !(m[1] in process.env)) process.env[m[1]] = m[2].replace(/^["']|["']$/g, "");
  }
}

const map = {
  apiKey: "FIREBASE_API_KEY",
  authDomain: "FIREBASE_AUTH_DOMAIN",
  projectId: "FIREBASE_PROJECT_ID",
  storageBucket: "FIREBASE_STORAGE_BUCKET",
  messagingSenderId: "FIREBASE_MESSAGING_SENDER_ID",
  appId: "FIREBASE_APP_ID",
};
const cfg = {};
const missing = [];
for (const [k, env] of Object.entries(map)) {
  if (!process.env[env]) missing.push(env); else cfg[k] = process.env[env];
}
if (missing.length) { console.error("Missing env vars: " + missing.join(", ") + "\nCopy .env.example to .env and fill it in."); process.exit(1); }

const out = "// GENERATED by build-config.js from .env — do not edit, do not commit.\nwindow.firebaseConfig = " + JSON.stringify(cfg, null, 2) + ";\n";
fs.writeFileSync(path.join(__dirname, "firebase-config.js"), out);
console.log("Wrote firebase-config.js for project " + cfg.projectId);
